nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: Clinical Genomics Stockholm
  description: Pipeline to analyse RNAseq from raredisease patients
  force: false
  is_nfcore: true
  name: tomte
  org: nf-core
  outdir: .
  version: 1.0dev
