repository_type: pipeline
template:
  author: lucpen
  description: Analyzing RNAseq data
  force: false
  is_nfcore: false
  name: tomte
  org: genomic-medicine-sweden
  outdir: .
  skip_features: null
  version: 2.2.1
