lint:
  files_exist:
    - assets/nf-core-tomte_logo_light.png
    - docs/images/nf-core-tomte_logo_light.png
    - docs/images/nf-core-tomte_logo_dark.png
    - docs/images/tomte_logo.eps
    - docs/images/tomte_pipeline_metromap.svg
    - docs/images/tomte_pipeline_metromap.png
    - conf/modules.config
    - .github/ISSUE_TEMPLATE/config.yml
  files_unchanged:
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .github/workflows/branch.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - assets/email_template.html
    - assets/email_template.txt
    - lib/NfcoreTemplate.groovy
    - docs/README.md
    - pyproject.toml
  modules_config: false
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
  template_strings: false
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: lucpen
  description: Analyzing RNAseq data
  force: false
  is_nfcore: false
  name: tomte
  org: genomic-medicine-sweden
  outdir: .
  version: 4.1.1
