lint:
  files_exist: false
    - assets/nf-core-tomte_logo_light.png
    - docs/images/nf-core-tomte_logo_light.png
    - docs/images/nf-core-tomte_logo_dark.png
    - docs/images/tomte_logo.eps
    - docs/images/tomte_pipeline_metromap.eps
    - docs/images/tomte_pipeline_metromap.png
    - conf/modules.config
    - .github/ISSUE_TEMPLATE/config.yml
  files_unchanged: false
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .github/workflows/branch.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - assets/email_template.html
    - assets/email_template.txt
    - lib/NfcoreTemplate.groovy
    - docs/README.md
    - pyproject.toml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
  modules_config: false
nf_core_version: 2.14.1
repository_type: pipeline
template:
  author: lucpen
  description: Analyzing RNAseq data
  name: tomte
  prefix: genomic-medicine-sweden
